# Generated by Django 5.2.17 on 2026-08-20 02:40

import apps.common.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "min_supported_version",
                    models.CharField(
                        default="1.0.0",
                        help_text="Клиент с версией ниже получает force_update.",
                        max_length=32,
                        verbose_name="Минимальная поддерживаемая версия",
                    ),
                ),
                (
                    "recommended_version",
                    models.CharField(
                        default="1.0.0",
                        max_length=32,
                        verbose_name="Рекомендуемая версия",
                    ),
                ),
                (
                    "android_store_url",
                    models.URLField(blank=True, verbose_name="Ссылка на Google Play"),
                ),
                (
                    "ios_store_url",
                    models.URLField(blank=True, verbose_name="Ссылка на App Store"),
                ),
                (
                    "maintenance_mode",
                    models.BooleanField(
                        default=False, verbose_name="Режим обслуживания"
                    ),
                ),
                (
                    "maintenance_message",
                    models.TextField(
                        blank=True,
                        help_text="Показывается на сплэше, пока включён режим обслуживания.",
                        verbose_name="Текст режима обслуживания",
                    ),
                ),
                (
                    "feature_flags",
                    models.JSONField(
                        blank=True,
                        default=apps.common.models.default_feature_flags,
                        help_text='Например: {"mortgage_calculator": true}',
                        verbose_name="Фича-флаги",
                    ),
                ),
                (
                    "constants",
                    models.JSONField(
                        blank=True,
                        default=apps.common.models.default_constants,
                        help_text="topup_bonus_rate, promotion_price_per_day, max_photos, max_videos, free_active_listings",
                        verbose_name="Константы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Конфигурация приложения",
                "verbose_name_plural": "Конфигурация приложения",
            },
        ),
        migrations.CreateModel(
            name="OnboardingSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Заголовок")),
                ("text", models.TextField(blank=True, verbose_name="Текст")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="onboarding/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Показывать"),
                ),
            ],
            options={
                "verbose_name": "Слайд онбординга",
                "verbose_name_plural": "Слайды онбординга",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="StaticPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "slug",
                    models.SlugField(
                        choices=[
                            ("terms", "Пользовательское соглашение"),
                            ("privacy", "Политика конфиденциальности"),
                            ("about", "О приложении"),
                            ("faq", "Частые вопросы"),
                            ("support", "Поддержка"),
                        ],
                        max_length=32,
                        unique=True,
                        verbose_name="Слаг",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                (
                    "content",
                    models.TextField(blank=True, verbose_name="Текст (markdown)"),
                ),
                (
                    "version",
                    models.CharField(
                        default="1",
                        help_text="Увеличивайте при изменении текста соглашений — у пользователей будет запрошено новое согласие.",
                        max_length=32,
                        verbose_name="Версия",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Опубликована"),
                ),
            ],
            options={
                "verbose_name": "Статическая страница",
                "verbose_name_plural": "Статические страницы",
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Тема")),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=16, verbose_name="Телефон для связи"
                    ),
                ),
                (
                    "app_version",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Версия приложения"
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("android", "Android"),
                            ("ios", "iOS"),
                            ("web", "Web"),
                        ],
                        max_length=16,
                        verbose_name="Платформа",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новое"),
                            ("in_progress", "В работе"),
                            ("closed", "Закрыто"),
                        ],
                        default="new",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="support_tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Обращение в поддержку",
                "verbose_name_plural": "Обращения в поддержку",
                "ordering": ["-created_at"],
            },
        ),
    ]
