# Generated by Django 5.2.17 on 2026-08-20 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("kyc.url_issued", "Выдана ссылка на документ"),
                            ("kyc.file_downloaded", "Документ скачан"),
                            ("kyc.reviewed", "Решение по заявке"),
                        ],
                        db_index=True,
                        max_length=64,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Тип объекта"
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="ID объекта"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="User-Agent"
                    ),
                ),
                (
                    "extra",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Подробности"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Когда"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Чьи данные",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись аудита",
                "verbose_name_plural": "Журнал аудита",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action", "-created_at"], name="audit_action_recent_idx"
                    ),
                    models.Index(
                        fields=["target_user", "-created_at"],
                        name="audit_target_recent_idx",
                    ),
                ],
            },
        ),
    ]
