# Generated by Django 5.1 on 2026-09-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='email_delivery_status',
            field=models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Отправлено'), ('failed', 'Ошибка отправки')], default='pending', max_length=16, verbose_name='Статус отправки email'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время отправки email'),
        ),
    ]
