# Generated by Django 5.2.17 on 2026-08-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_auditlog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auditlog",
            old_name="object_id",
            new_name="target_id",
        ),
        migrations.RenameField(
            model_name="auditlog",
            old_name="object_type",
            new_name="target_type",
        ),
        migrations.AddField(
            model_name="auditlog",
            name="changes",
            field=models.JSONField(blank=True, default=dict, verbose_name="Изменения"),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="request_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, verbose_name="ID запроса"
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                db_index=True, max_length=64, verbose_name="Действие"
            ),
        ),
    ]
