# Generated by Django 5.2.17 on 2026-08-20 10:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_backfill_price_usd"),
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "token",
                    models.CharField(max_length=255, unique=True, verbose_name="Токен"),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("android", "Android"), ("ios", "iOS")],
                        max_length=16,
                        verbose_name="Платформа",
                    ),
                ),
                (
                    "app_version",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Версия приложения"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активен"
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Последняя активность",
                    ),
                ),
            ],
            options={
                "verbose_name": "Устройство",
                "verbose_name_plural": "Устройства",
                "ordering": ["-last_seen_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "push_enabled",
                    models.BooleanField(default=True, verbose_name="Push-уведомления"),
                ),
                (
                    "price_drop_enabled",
                    models.BooleanField(default=True, verbose_name="Снижение цены"),
                ),
                (
                    "saved_filter_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Новые объекты по фильтру"
                    ),
                ),
                (
                    "listing_moderated_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Модерация объявлений"
                    ),
                ),
                (
                    "promotion_expiring_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Продвижение заканчивается"
                    ),
                ),
                (
                    "wallet_topup_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Пополнение кошелька"
                    ),
                ),
                (
                    "system_enabled",
                    models.BooleanField(default=True, verbose_name="Системные"),
                ),
            ],
            options={
                "verbose_name": "Настройки уведомлений",
                "verbose_name_plural": "Настройки уведомлений",
            },
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="notification_user_unread_idx",
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Прочитано"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="title",
            field=models.CharField(max_length=140, verbose_name="Заголовок"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("price_drop", "Снижение цены"),
                    ("saved_filter_match", "Новые объекты по фильтру"),
                    ("listing_moderated", "Модерация объявления"),
                    ("promotion_expiring", "Продвижение заканчивается"),
                    ("wallet_topup", "Пополнение кошелька"),
                    ("system", "Системное"),
                ],
                db_index=True,
                default="system",
                max_length=32,
                verbose_name="Тип",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read", "-created_at"],
                name="notification_user_unread_idx",
            ),
        ),
        migrations.AddField(
            model_name="devicetoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="notificationsettings",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_settings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddIndex(
            model_name="devicetoken",
            index=models.Index(
                fields=["user", "is_active"], name="device_user_active_idx"
            ),
        ),
    ]
