# Generated by Django 5.2.17 on 2026-09-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_backfill_settings_and_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationsettings",
            name="new_message_enabled",
            field=models.BooleanField(default=True, verbose_name="Новые сообщения"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("new_message", "Новое сообщение"),
                    ("price_drop", "Снижение цены"),
                    ("saved_filter_match", "Новые объекты по фильтру"),
                    ("listing_moderated", "Модерация объявления"),
                    ("promotion_expiring", "Продвижение заканчивается"),
                    ("wallet_topup", "Пополнение кошелька"),
                    ("system", "Системное"),
                ],
                db_index=True,
                default="system",
                max_length=32,
                verbose_name="Тип",
            ),
        ),
    ]
