# Generated by Django 5.2.17 on 2026-09-03 05:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0026_listing_positive_numbers"),
        ("notifications", "0004_new_message_notifications"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="devicetoken",
            name="device_id",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                unique=True,
                verbose_name="ID установки",
            ),
        ),
        migrations.AddField(
            model_name="devicetoken",
            name="locale",
            field=models.CharField(
                choices=[("ru", "Русский"), ("ky", "Кыргызча")],
                default="ru",
                max_length=8,
                verbose_name="Язык",
            ),
        ),
        migrations.AddField(
            model_name="devicetoken",
            name="timezone",
            field=models.CharField(
                default="Asia/Bishkek", max_length=64, verbose_name="Часовой пояс"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="event_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Идемпотентность fan-out: один пользователь получает событие один раз.",
                max_length=160,
                verbose_name="Ключ доменного события",
            ),
        ),
        migrations.AddField(
            model_name="notificationsettings",
            name="price_drop_viewed_enabled",
            field=models.BooleanField(
                default=True, verbose_name="Снижение цены просмотренных объектов"
            ),
        ),
        migrations.AlterField(
            model_name="devicetoken",
            name="token",
            field=models.CharField(max_length=512, unique=True, verbose_name="Токен"),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                condition=models.Q(("event_key", ""), _negated=True),
                fields=("user", "event_key"),
                name="notification_user_event_unique",
            ),
        ),
    ]
