# Generated by Django 5.2.17 on 2026-09-03 06:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_push_foundation"),
    ]

    operations = [
        migrations.CreateModel(
            name="PushOutbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("processing", "В обработке"),
                            ("sent", "Отправлено"),
                            ("retry", "Повтор"),
                            ("failed", "Не удалось"),
                            ("skipped_disabled", "Пропущено: push выключен"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Состояние",
                    ),
                ),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Попыток"),
                ),
                (
                    "next_attempt_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Следующая попытка",
                    ),
                ),
                (
                    "locked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Взято в работу"
                    ),
                ),
                (
                    "last_error",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Последняя ошибка",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Отправлено"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "notification",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_outbox",
                        to="notifications.notification",
                        verbose_name="Уведомление",
                    ),
                ),
            ],
            options={
                "verbose_name": "Очередь push",
                "verbose_name_plural": "Очередь push",
                "ordering": ["next_attempt_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["status", "next_attempt_at"], name="push_outbox_due_idx"
                    )
                ],
            },
        ),
    ]
