# Generated by Django 5.2.17 on 2026-08-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/%Y/%m/", verbose_name="Аватар"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="iin",
            field=models.CharField(
                blank=True,
                help_text="Заполняется только при pro-регистрации.",
                max_length=14,
                verbose_name="ИИН",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, max_length=120, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                help_text="Хранится в E.164, например +996700123456.",
                max_length=16,
                unique=True,
                verbose_name="Телефон",
            ),
        ),
    ]
