# Generated by Django 5.2.17 on 2026-08-20 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_updated_at_alter_user_avatar_alter_user_iin_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtpCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True, max_length=16, verbose_name="Телефон"
                    ),
                ),
                (
                    "code_hash",
                    models.CharField(max_length=128, verbose_name="Хеш кода"),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("login", "Вход"),
                            ("pro_register", "Регистрация исполнителя"),
                        ],
                        default="login",
                        max_length=16,
                        verbose_name="Назначение",
                    ),
                ),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Неудачных попыток"
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(default=False, verbose_name="Использован"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Действует до")),
            ],
            options={
                "verbose_name": "Код подтверждения",
                "verbose_name_plural": "Коды подтверждения",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["phone", "purpose", "-created_at"],
                        name="otp_lookup_idx",
                    )
                ],
            },
        ),
    ]
