# Generated by Django 5.2.17 on 2026-08-20 03:39

import apps.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0003_otpcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="whatsapp_phone",
            field=models.CharField(
                blank=True,
                help_text="Номер для связи в WhatsApp, E.164.",
                max_length=16,
                null=True,
                verbose_name="WhatsApp",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="iin",
            field=models.CharField(
                blank=True,
                help_text="Заполняется только при pro-регистрации, 14 цифр.",
                max_length=14,
                validators=[apps.users.validators.validate_iin],
                verbose_name="ИИН",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("iin", ""), _negated=True),
                fields=("iin",),
                name="user_iin_unique",
            ),
        ),
    ]
