# Generated by Django 5.2.17 on 2026-08-20 03:50

import apps.common.storages
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_whatsapp_phone_alter_user_iin_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SellerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Название компании"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="sellers/%Y/%m/",
                        verbose_name="Логотип",
                    ),
                ),
                ("about", models.TextField(blank=True, verbose_name="О себе")),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        verbose_name="Рейтинг",
                    ),
                ),
                (
                    "reviews_count",
                    models.PositiveIntegerField(default=0, verbose_name="Отзывов"),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, verbose_name="Личность подтверждена"
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Подтверждено"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль продавца",
                "verbose_name_plural": "Профили продавцов",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IdentityVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "selfie",
                    models.FileField(
                        storage=apps.common.storages.private_storage,
                        upload_to="kyc/%Y/%m/",
                        verbose_name="Селфи",
                    ),
                ),
                (
                    "document_front",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=apps.common.storages.private_storage,
                        upload_to="kyc/%Y/%m/",
                        verbose_name="Документ, лицевая сторона",
                    ),
                ),
                (
                    "document_back",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=apps.common.storages.private_storage,
                        upload_to="kyc/%Y/%m/",
                        verbose_name="Документ, оборот",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[("passport", "Паспорт"), ("id_card", "ID-карта")],
                        default="passport",
                        max_length=16,
                        verbose_name="Тип документа",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "На проверке"),
                            ("approved", "Подтверждена"),
                            ("rejected", "Отклонена"),
                            ("expired", "Истекла"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "reject_reason",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Причина отказа"
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, verbose_name="Комментарий модератора"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Проверено"
                    ),
                ),
                (
                    "purge_after",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Удалить файлы после"
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_verifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Проверил",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identity_verifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проверка личности",
                "verbose_name_plural": "Проверки личности",
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_review_identity", "Может проверять документы пользователей")
                ],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="kyc_user_recent_idx"
                    ),
                    models.Index(
                        fields=["status", "created_at"], name="kyc_status_created_idx"
                    ),
                ],
            },
        ),
    ]
