# Generated by Django 5.2.17 on 2026-08-22 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_sellerprofile_identityverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_trusted",
            field=models.BooleanField(
                default=False,
                help_text="Объявления публикуются сразу, минуя модерацию.",
                verbose_name="Доверенный",
            ),
        ),
    ]
