# Generated by Django 5.2.17 on 2026-08-22 07:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0017_promotions"),
        ("users", "0006_listing_lifecycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerprofile",
            name="experience_years",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Опыт, лет"),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="instagram",
            field=models.CharField(blank=True, max_length=64, verbose_name="Instagram"),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="telegram",
            field=models.CharField(blank=True, max_length=64, verbose_name="Telegram"),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="whatsapp",
            field=models.CharField(blank=True, max_length=32, verbose_name="WhatsApp"),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="work_districts",
            field=models.ManyToManyField(
                blank=True,
                related_name="sellers",
                to="catalog.district",
                verbose_name="Районы работы",
            ),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="working_hours",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Часы работы"
            ),
        ),
        migrations.CreateModel(
            name="ContactEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Когда"
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_events",
                        to="catalog.listing",
                        verbose_name="Объявление",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто смотрел",
                    ),
                ),
            ],
            options={
                "verbose_name": "Раскрытие контакта",
                "verbose_name_plural": "Раскрытия контактов",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="contact_user_recent_idx"
                    ),
                    models.Index(
                        fields=["listing", "-created_at"], name="contact_listing_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Оценка",
                    ),
                ),
                ("text", models.TextField(blank=True, verbose_name="Текст")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "На модерации"),
                            ("published", "Опубликован"),
                            ("rejected", "Отклонён"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "moderator_comment",
                    models.TextField(blank=True, verbose_name="Комментарий модератора"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_written",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to="catalog.listing",
                        verbose_name="Объявление",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Продавец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["seller", "status", "-created_at"],
                        name="review_seller_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("seller", "author"),
                        name="review_unique_author_per_seller",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("rating__gte", 1), ("rating__lte", 5)),
                        name="review_rating_range",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SellerVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "documents",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Документы"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "На проверке"),
                            ("approved", "Подтверждена"),
                            ("rejected", "Отклонена"),
                            ("expired", "Истекла"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Когда проверено"
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seller_verifications_reviewed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто проверил",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_verifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Продавец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на подтверждение продавца",
                "verbose_name_plural": "Заявки на подтверждение продавцов",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"], name="seller_verif_status_idx"
                    )
                ],
            },
        ),
    ]
