# Generated by Django 5.2.17 on 2026-08-22 08:34

import apps.common.fields
import apps.users.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_seller_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="iin",
            field=apps.common.fields.EncryptedCharField(
                blank=True,
                help_text="Заполняется только при pro-регистрации, 14 цифр.",
                max_length=255,
                validators=[apps.users.validators.validate_iin],
                verbose_name="ИИН",
            ),
        ),
    ]
