# Generated by Django 5.2.17 on 2026-08-22 08:36

import apps.common.storages
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_encrypt_existing_iin"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Готовится"),
                            ("ready", "Готово"),
                            ("failed", "Ошибка"),
                            ("expired", "Ссылка истекла"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=apps.common.storages.private_storage,
                        upload_to="exports/%Y/%m/",
                        verbose_name="Файл",
                    ),
                ),
                (
                    "size_bytes",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Размер"
                    ),
                ),
                (
                    "error",
                    models.CharField(blank=True, max_length=255, verbose_name="Ошибка"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ссылка истекает"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Создана"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Готова"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_exports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выгрузка данных",
                "verbose_name_plural": "Выгрузки данных",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("personal_data", "Обработка персональных данных"),
                            ("marketing", "Рекламные рассылки"),
                            ("cookies", "Аналитика и cookies"),
                        ],
                        default="personal_data",
                        max_length=32,
                        verbose_name="Тип согласия",
                    ),
                ),
                (
                    "document_version",
                    models.CharField(max_length=32, verbose_name="Версия документа"),
                ),
                ("granted", models.BooleanField(default=True, verbose_name="Дано")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="User-Agent"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Когда"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Согласие пользователя",
                "verbose_name_plural": "Согласия пользователей",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "consent_type", "-created_at"],
                        name="consent_user_type_idx",
                    )
                ],
            },
        ),
    ]
