# Generated by Django 5.2.17 on 2026-09-02 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_otpcode_purpose"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpcode",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("login", "Вход"),
                    ("register", "Регистрация"),
                    ("password_reset", "Восстановление пароля"),
                    ("pro_register", "Регистрация исполнителя"),
                ],
                default="login",
                max_length=16,
                verbose_name="Назначение",
            ),
        ),
    ]
