# Generated by Django 5.2.17 on 2026-09-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_otpcode_purpose"),
    ]

    operations = [
        migrations.AddField(
            model_name="otpcode",
            name="request_id",
            field=models.CharField(
                blank=True, default="", max_length=128, verbose_name="ID запроса шлюза"
            ),
        ),
    ]
