# Generated by Django 5.2.17 on 2026-09-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_otpcode_request_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_cover",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_covers/%Y/%m/",
                verbose_name="Обложка профиля",
            ),
        ),
    ]
