# Generated by Django 5.2.17 on 2026-09-03 05:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0026_listing_positive_numbers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTasteProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                ("deal_type_weights", models.JSONField(blank=True, default=dict)),
                ("property_type_weights", models.JSONField(blank=True, default=dict)),
                ("rooms_distribution", models.JSONField(blank=True, default=dict)),
                ("district_weights", models.JSONField(blank=True, default=dict)),
                (
                    "price_p25",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "price_p75",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("last_computed_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.CharField(default="v1", max_length=32)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taste_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Taste Profile",
                "verbose_name_plural": "User Taste Profiles",
            },
        ),
        migrations.CreateModel(
            name="RecommendationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        db_index=True, max_length=128, verbose_name="Session ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("search", "Search"),
                            ("view", "View Listing"),
                            ("favorite", "Favorite"),
                            ("seller_profile", "View Seller Profile"),
                            ("contact", "Reveal Contact"),
                            ("chat", "Chat Started"),
                            ("reel_impression", "Reel Impression"),
                            ("reel_watch", "Reel Watch"),
                            ("reel_skip", "Immediate Skip"),
                            ("reel_replay", "Reel Replay"),
                            ("not_interested", "Not Interested"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("context", models.JSONField(blank=True, default=dict)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created at",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_events",
                        to="catalog.listing",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recommendation Event",
                "verbose_name_plural": "Recommendation Events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="recommendat_user_id_70ec89_idx",
                    ),
                    models.Index(
                        fields=["session_id", "created_at"],
                        name="recommendat_session_a030e8_idx",
                    ),
                    models.Index(
                        fields=["listing", "created_at"],
                        name="recommendat_listing_86d09c_idx",
                    ),
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="recommendat_event_t_f67c70_idx",
                    ),
                ],
            },
        ),
    ]
