# Generated by Django 5.2.17 on 2026-09-03 06:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0026_listing_positive_numbers"),
        ("recommendations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendationevent",
            name="client_event_id",
            field=models.UUIDField(
                blank=True, db_index=True, null=True, verbose_name="Client Event ID"
            ),
        ),
        migrations.AddField(
            model_name="recommendationevent",
            name="feed_session_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=128,
                verbose_name="Feed Session ID",
            ),
        ),
        migrations.AddConstraint(
            model_name="recommendationevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_event_id__isnull", False)),
                fields=("client_event_id",),
                name="recommendation_event_unique_client_id",
            ),
        ),
    ]
