# Generated by Django 5.2.17 on 2026-08-20 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_backfill_price_usd"),
        ("engagement", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Заголовок")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Подзаголовок"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=160, unique=True, verbose_name="Слаг"),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="collections/%Y/%m/",
                        verbose_name="Обложка",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "mode",
                    models.CharField(
                        choices=[("query", "По фильтру"), ("manual", "Ручной список")],
                        default="query",
                        max_length=16,
                        verbose_name="Режим",
                    ),
                ),
                (
                    "params",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Для режима «По фильтру».",
                        verbose_name="Параметры фильтра",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
            ],
            options={
                "verbose_name": "Подборка",
                "verbose_name_plural": "Подборки",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CollectionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="engagement.collection",
                        verbose_name="Подборка",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_items",
                        to="catalog.listing",
                        verbose_name="Объявление",
                    ),
                ),
            ],
            options={
                "verbose_name": "Объект подборки",
                "verbose_name_plural": "Объекты подборки",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="collection",
            name="listings",
            field=models.ManyToManyField(
                blank=True,
                related_name="collections",
                through="engagement.CollectionItem",
                to="catalog.listing",
                verbose_name="Объявления",
            ),
        ),
        migrations.CreateModel(
            name="SavedFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("params", models.JSONField(default=dict, verbose_name="Параметры")),
                (
                    "notify_on_new",
                    models.BooleanField(
                        default=True, verbose_name="Уведомлять о новых"
                    ),
                ),
                (
                    "last_notified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последнее уведомление"
                    ),
                ),
                (
                    "matches_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Подходящих объектов"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_filters",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сохранённый фильтр",
                "verbose_name_plural": "Сохранённые фильтры",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="collectionitem",
            constraint=models.UniqueConstraint(
                fields=("collection", "listing"), name="collection_item_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="savedfilter",
            index=models.Index(
                fields=["notify_on_new"], name="saved_filter_notify_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="savedfilter",
            unique_together={("user", "name")},
        ),
    ]
