# Generated by Django 5.2.17 on 2026-08-20 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_backfill_price_usd"),
        ("engagement", "0002_collection_collectionitem_collection_listings_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="favourite",
            name="favourite_unique",
        ),
        migrations.RemoveConstraint(
            model_name="viewhistory",
            name="view_history_unique",
        ),
        migrations.AlterField(
            model_name="favourite",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favourited_by",
                to="catalog.listing",
                verbose_name="Объявление",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favourite",
            unique_together={("user", "listing")},
        ),
        migrations.AlterUniqueTogether(
            name="viewhistory",
            unique_together={("user", "listing")},
        ),
    ]
