# Generated by Django 5.2.17 on 2026-08-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagement", "0003_favourite_and_history_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="favourite",
            name="price_at_add",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                editable=False,
                max_digits=12,
                null=True,
                verbose_name="Цена при добавлении, USD",
            ),
        ),
    ]
