# Generated by Django 5.2.17 on 2026-09-03 05:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagement", "0005_backfill_price_at_add"),
    ]

    operations = [
        migrations.AddField(
            model_name="viewhistory",
            name="first_viewed_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Впервые просмотрено"
            ),
        ),
        migrations.AddField(
            model_name="viewhistory",
            name="view_count",
            field=models.PositiveIntegerField(default=1, verbose_name="Просмотров"),
        ),
    ]
