# Generated by Django 5.2.17 on 2026-08-20 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "balance",
                    models.BigIntegerField(default=0, verbose_name="Баланс, кирпичей"),
                ),
            ],
            options={
                "verbose_name": "Кошелёк",
                "verbose_name_plural": "Кошельки",
            },
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                ("amount", models.BigIntegerField(verbose_name="Сумма, кирпичей")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("topup", "Пополнение"),
                            ("spend", "Списание"),
                            ("bonus", "Бонусы"),
                        ],
                        max_length=16,
                        verbose_name="Тип операции",
                    ),
                ),
                ("label", models.CharField(max_length=255, verbose_name="Описание")),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        unique=True,
                        verbose_name="Ключ идемпотентности",
                    ),
                ),
            ],
            options={
                "verbose_name": "Операция по кошельку",
                "verbose_name_plural": "Операции по кошельку",
                "ordering": ["-created_at"],
            },
        ),
    ]
