"""Леджер: balance_after, ссылка на объект операции, запрет минуса."""

# Generated by Django 5.2.17 on 2026-08-21 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wallettransaction",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Операция по кошельку",
                "verbose_name_plural": "Операции по кошельку",
            },
        ),
        migrations.RemoveField(
            model_name="wallettransaction",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="balance_after",
            field=models.BigIntegerField(
                default=0, verbose_name="Баланс после операции"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="related_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
                verbose_name="Тип объекта",
            ),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="related_object_id",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="ID объекта"
            ),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Создана"
            ),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="idempotency_key",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Ключ идемпотентности",
            ),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="label",
            field=models.CharField(max_length=200, verbose_name="Описание"),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(
                fields=["wallet", "kind", "-created_at"], name="wallet_tx_kind_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="wallet",
            constraint=models.CheckConstraint(
                condition=models.Q(("balance__gte", 0)),
                name="wallet_balance_non_negative",
            ),
        ),
    ]
