# Generated by Django 5.2.17 on 2026-08-21 10:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_backfill_balance_after"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentProviderConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "code",
                    models.SlugField(max_length=32, unique=True, verbose_name="Код"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="payments/%Y/%m/",
                        verbose_name="Логотип",
                    ),
                ),
                (
                    "deeplink_template",
                    models.CharField(
                        blank=True,
                        help_text="Подстановки: {payment_url}, {provider_ref}, {amount}. Например: mbank://pay?target={provider_ref}&amount={amount}",
                        max_length=255,
                        verbose_name="Шаблон диплинка",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
            ],
            options={
                "verbose_name": "Способ оплаты",
                "verbose_name_plural": "Способы оплаты",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Идентификатор",
                    ),
                ),
                (
                    "amount_kgs",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Сумма, сом"
                    ),
                ),
                ("bricks", models.BigIntegerField(default=0, verbose_name="Кирпичей")),
                (
                    "bonus_bricks",
                    models.BigIntegerField(default=0, verbose_name="Бонусных кирпичей"),
                ),
                ("provider", models.CharField(max_length=32, verbose_name="Провайдер")),
                (
                    "provider_ref",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=128,
                        null=True,
                        verbose_name="ID платежа у провайдера",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает оплаты"),
                            ("succeeded", "Оплачен"),
                            ("failed", "Не прошёл"),
                            ("expired", "Просрочен"),
                            ("refunded", "Возвращён"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="Ключ идемпотентности"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Оплачен"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Действителен до"
                    ),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Ответ провайдера"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пополнение",
                "verbose_name_plural": "Пополнения",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "Входящий"), ("out", "Исходящий")],
                        max_length=8,
                        verbose_name="Направление",
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Эндпоинт"
                    ),
                ),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, verbose_name="Тело"),
                ),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Код ответа"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Создан"
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="billing.payment",
                        verbose_name="Платёж",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог платежа",
                "verbose_name_plural": "Логи платежей",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["user", "-created_at"], name="payment_user_recent_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["status", "expires_at"], name="payment_status_expiry_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentlog",
            index=models.Index(
                fields=["payment", "-created_at"], name="payment_log_recent_idx"
            ),
        ),
    ]
