# Generated by Django 5.2.17 on 2026-08-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_payments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallettransaction",
            name="related_object_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=64,
                null=True,
                verbose_name="ID объекта",
            ),
        ),
    ]
