# Generated by Django 5.2.17 on 2026-08-22 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0006_related_object_id_as_text"),
        ("catalog", "0017_promotions"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromotionOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "code",
                    models.SlugField(max_length=32, unique=True, verbose_name="Код"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "price_per_day_bricks",
                    models.BigIntegerField(verbose_name="Цена за день, кирпичей"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
            ],
            options={
                "verbose_name": "Опция продвижения",
                "verbose_name_plural": "Опции продвижения",
                "ordering": ["order", "code"],
            },
        ),
        migrations.CreateModel(
            name="PromotionPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "code",
                    models.SlugField(max_length=32, unique=True, verbose_name="Код"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "price_per_day_bricks",
                    models.BigIntegerField(verbose_name="Цена за день, кирпичей"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
            ],
            options={
                "verbose_name": "Пакет продвижения",
                "verbose_name_plural": "Пакеты продвижения",
                "ordering": ["order", "code"],
            },
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                ("days", models.PositiveSmallIntegerField(verbose_name="Дней")),
                (
                    "options",
                    models.JSONField(blank=True, default=list, verbose_name="Опции"),
                ),
                (
                    "cost_bricks",
                    models.BigIntegerField(verbose_name="Стоимость, кирпичей"),
                ),
                ("starts_at", models.DateTimeField(verbose_name="Начало")),
                (
                    "ends_at",
                    models.DateTimeField(db_index=True, verbose_name="Окончание"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Действует"),
                            ("finished", "Завершено"),
                            ("refunded", "Возвращено"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "expiry_notified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Уведомление отправлено"
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to="catalog.listing",
                        verbose_name="Объявление",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promotions",
                        to="billing.wallettransaction",
                        verbose_name="Операция списания",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promotions",
                        to="billing.promotionpackage",
                        verbose_name="Пакет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продвижение",
                "verbose_name_plural": "Продвижения",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "ends_at"], name="promotion_status_ends_idx"
                    ),
                    models.Index(
                        fields=["listing", "-created_at"], name="promotion_listing_idx"
                    ),
                ],
            },
        ),
    ]
