# Generated by Django 5.2.17 on 2026-08-22 05:02

import apps.billing.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0008_promotion_catalog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tariff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "code",
                    models.SlugField(max_length=32, unique=True, verbose_name="Код"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "price_bricks_per_month",
                    models.BigIntegerField(
                        default=0, verbose_name="Цена, кирпичей в месяц"
                    ),
                ),
                (
                    "listings_limit",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="0 — без ограничений.",
                        verbose_name="Лимит активных объявлений",
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=apps.billing.models.default_tariff_features,
                        verbose_name="Возможности",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тариф",
                "verbose_name_plural": "Тарифы",
                "ordering": ["order", "code"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                ("starts_at", models.DateTimeField(verbose_name="Начало")),
                (
                    "ends_at",
                    models.DateTimeField(db_index=True, verbose_name="Окончание"),
                ),
                (
                    "is_auto_renew",
                    models.BooleanField(default=True, verbose_name="Автопродление"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Действует"),
                            ("expired", "Истекла"),
                            ("cancelled", "Отменена"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "renewal_attempted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Попытка продления"
                    ),
                ),
                (
                    "auto_bumped_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Автоподъём"
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="billing.wallettransaction",
                        verbose_name="Операция списания",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "tariff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="billing.tariff",
                        verbose_name="Тариф",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подписка",
                "verbose_name_plural": "Подписки",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status", "-ends_at"],
                        name="subscription_user_idx",
                    ),
                    models.Index(
                        fields=["status", "ends_at"],
                        name="subscription_status_ends_idx",
                    ),
                ],
            },
        ),
    ]
