# Generated by Django 5.2.17 on 2026-08-20 02:28

import apps.catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HouseSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "code",
                    models.CharField(max_length=32, unique=True, verbose_name="Код"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Серия дома",
                "verbose_name_plural": "Серии домов",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ListingMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.catalog.models.listing_media_path,
                        verbose_name="Файл",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("photo", "Фото"), ("video", "Видео")],
                        default="photo",
                        max_length=8,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_cover",
                    models.BooleanField(default=False, verbose_name="Обложка"),
                ),
                (
                    "allow_download",
                    models.BooleanField(
                        default=True, verbose_name="Разрешить скачивание"
                    ),
                ),
            ],
            options={
                "verbose_name": "Медиа объявления",
                "verbose_name_plural": "Медиа объявлений",
                "ordering": ["listing_id", "order"],
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "slug",
                    models.SlugField(max_length=120, unique=True, verbose_name="Слаг"),
                ),
                (
                    "city",
                    models.CharField(
                        default="Бишкек", max_length=100, verbose_name="Город"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Широта",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Долгота",
                    ),
                ),
            ],
            options={
                "verbose_name": "Район",
                "verbose_name_plural": "Районы",
                "ordering": ["city", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("city", "name"), name="district_unique_in_city"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=140, unique=True, verbose_name="Слаг"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("house", "Дома"),
                            ("apartment", "Квартиры"),
                            ("plot", "Участки"),
                            ("new_building", "Новостройки"),
                            ("room", "Комната"),
                            ("commercial", "Коммерция"),
                        ],
                        max_length=16,
                        verbose_name="Тип объекта",
                    ),
                ),
                (
                    "seller_kind",
                    models.CharField(
                        choices=[
                            ("owner", "Только собственник"),
                            ("realtor", "Риелторы"),
                            ("agency", "Агентство недвижимости"),
                        ],
                        default="owner",
                        max_length=16,
                        verbose_name="Кто продаёт",
                    ),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=255, verbose_name="Адрес"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Цена"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("USD", "Доллар США"), ("KGS", "Сом")],
                        default="USD",
                        max_length=3,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Старая цена",
                    ),
                ),
                (
                    "rooms",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Комнат"),
                ),
                (
                    "area",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Площадь, м²"
                    ),
                ),
                (
                    "floor",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Этаж"),
                ),
                (
                    "floors",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Этажность"
                    ),
                ),
                (
                    "is_secondary",
                    models.BooleanField(default=False, verbose_name="Вторичка"),
                ),
                (
                    "below_market",
                    models.BooleanField(default=False, verbose_name="Ниже рынка"),
                ),
                (
                    "red_book",
                    models.BooleanField(default=False, verbose_name="Красная книга"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "builder",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Застройщик"
                    ),
                ),
                (
                    "agent_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Кто показывает объект"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("pending", "На модерации"),
                            ("active", "Опубликовано"),
                            ("rejected", "Отклонено"),
                            ("archived", "В архиве"),
                            ("sold", "Продано"),
                        ],
                        default="draft",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Опубликовано"
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(default=0, verbose_name="Просмотров"),
                ),
                (
                    "promoted_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Продвигается до"
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="listings",
                        to="catalog.district",
                        verbose_name="Район",
                    ),
                ),
            ],
            options={
                "verbose_name": "Объявление",
                "verbose_name_plural": "Объявления",
                "ordering": ["-created_at"],
            },
        ),
    ]
