# Generated by Django 5.2.17 on 2026-08-20 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listings",
                to="catalog.houseseries",
                verbose_name="Серия дома",
            ),
        ),
        migrations.AddField(
            model_name="listingmedia",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="catalog.listing",
                verbose_name="Объявление",
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["status", "-published_at"], name="listing_status_pub_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["kind", "price"], name="listing_kind_price_idx"),
        ),
        migrations.AddConstraint(
            model_name="listingmedia",
            constraint=models.UniqueConstraint(
                fields=("listing", "order"), name="listing_media_unique_order"
            ),
        ),
    ]
