"""Финализация переезда района на FK города."""

# Generated by Django 5.2.17 on 2026-08-20 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_move_districts_to_city_fk"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="district",
            options={
                "ordering": ["order", "name"],
                "verbose_name": "Район",
                "verbose_name_plural": "Районы",
            },
        ),
        migrations.AlterModelOptions(
            name="houseseries",
            options={
                "ordering": ["order", "code"],
                "verbose_name": "Серия дома",
                "verbose_name_plural": "Серии домов",
            },
        ),
        migrations.AlterUniqueTogether(
            name="district",
            unique_together={("city", "slug")},
        ),
        migrations.AlterField(
            model_name="district",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="districts",
                to="catalog.city",
                verbose_name="Город",
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="slug",
            field=models.SlugField(max_length=120, verbose_name="Слаг"),
        ),
        migrations.RemoveField(
            model_name="district",
            name="city_legacy",
        ),
    ]
