"""Поля объявления и медиа: гео, лимиты, счётчики, поисковый вектор."""

# Generated by Django 5.2.17 on 2026-08-20 06:33

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from apps.catalog.migrations_utils import PostgresOnlyAddIndex


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_listing_city_and_builder_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listingmedia",
            options={
                "ordering": ("order", "id"),
                "verbose_name": "Медиа объявления",
                "verbose_name_plural": "Медиа объявлений",
            },
        ),
        migrations.RemoveIndex(
            model_name="listing",
            name="listing_kind_price_idx",
        ),
        migrations.RemoveField(
            model_name="listingmedia",
            name="allow_download",
        ),
        migrations.AddField(
            model_name="listing",
            name="allow_media_download",
            field=models.BooleanField(
                default=True, verbose_name="Разрешить скачивание фото"
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="contact_phone",
            field=models.CharField(
                blank=True, max_length=16, verbose_name="Контактный телефон"
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="expires_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Снять с публикации"
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="favourites_count",
            field=models.PositiveIntegerField(default=0, verbose_name="В избранном"),
        ),
        migrations.AddField(
            model_name="listing",
            name="land_area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Площадь участка, соток",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Широта",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Долгота",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="rejection_reason",
            field=models.TextField(blank=True, verbose_name="Причина отклонения"),
        ),
        migrations.AddField(
            model_name="listing",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True, editable=False, null=True, verbose_name="Поисковый вектор"
            ),
        ),
        migrations.AddField(
            model_name="listingmedia",
            name="duration_seconds",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Длительность, с"
            ),
        ),
        migrations.AddField(
            model_name="listingmedia",
            name="height",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Высота"
            ),
        ),
        migrations.AddField(
            model_name="listingmedia",
            name="size_bytes",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="Размер, байт"
            ),
        ),
        migrations.AddField(
            model_name="listingmedia",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="listings/thumbnails/%Y/%m/",
                verbose_name="Превью",
            ),
        ),
        migrations.AddField(
            model_name="listingmedia",
            name="width",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Ширина"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="area",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="Площадь, м²"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="contact_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Контактное лицо"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="currency",
            field=models.CharField(
                choices=[("USD", "USD"), ("KGS", "KGS")],
                default="USD",
                max_length=3,
                verbose_name="Валюта",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="old_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Зачёркнутая цена в карточке.",
                max_digits=12,
                null=True,
                verbose_name="Старая цена",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="promoted_until",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="Продвигается до"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=140, unique=True, verbose_name="Слаг"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("pending", "На модерации"),
                    ("active", "Опубликовано"),
                    ("rejected", "Отклонено"),
                    ("archived", "В архиве"),
                    ("sold", "Продано"),
                ],
                db_index=True,
                default="draft",
                max_length=16,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="listingmedia",
            name="file",
            field=models.FileField(upload_to="listings/%Y/%m/", verbose_name="Файл"),
        ),
        migrations.AlterField(
            model_name="listingmedia",
            name="kind",
            field=models.CharField(
                choices=[("photo", "photo"), ("video", "video")],
                default="photo",
                max_length=8,
                verbose_name="Тип",
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["status", "district", "kind"], name="listing_status_geo_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["status", "price"], name="listing_status_price_idx"
            ),
        ),
        PostgresOnlyAddIndex(
            model_name="listing",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="listing_search_vector_idx"
            ),
        ),
        PostgresOnlyAddIndex(
            model_name="listing",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["address"],
                name="listing_address_trgm_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddConstraint(
            model_name="listingmedia",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_cover", True)),
                fields=("listing",),
                name="listing_media_single_cover",
            ),
        ),
    ]
