# Generated by Django 5.2.17 on 2026-08-20 06:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_finalize_listing_relations"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="price_usd",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=2,
                editable=False,
                max_digits=12,
                null=True,
                verbose_name="Цена в USD",
            ),
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "currency_from",
                    models.CharField(
                        choices=[("USD", "USD"), ("KGS", "KGS")],
                        max_length=3,
                        verbose_name="Из валюты",
                    ),
                ),
                (
                    "currency_to",
                    models.CharField(
                        choices=[("USD", "USD"), ("KGS", "KGS")],
                        max_length=3,
                        verbose_name="В валюту",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=6, max_digits=12, verbose_name="Курс"
                    ),
                ),
                (
                    "fetched_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Загружен",
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс валюты",
                "verbose_name_plural": "Курсы валют",
                "ordering": ["-fetched_at"],
                "get_latest_by": "fetched_at",
                "indexes": [
                    models.Index(
                        fields=["currency_from", "currency_to", "-fetched_at"],
                        name="rate_pair_recent_idx",
                    )
                ],
            },
        ),
    ]
