# Generated by Django 5.2.17 on 2026-08-22 02:18

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_backfill_price_usd"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listing",
            options={
                "base_manager_name": "all_objects",
                "ordering": ["-created_at"],
                "verbose_name": "Объявление",
                "verbose_name_plural": "Объявления",
            },
        ),
        migrations.AlterModelManagers(
            name="listing",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="listing",
            name="bumped_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Последний подъём"
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Удалено"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Площадь, м²",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="listings",
                to="catalog.city",
                verbose_name="Город",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="listings",
                to="catalog.district",
                verbose_name="Район",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Цена",
            ),
        ),
    ]
