# Generated by Django 5.2.17 on 2026-08-22 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_listing_media_processing"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RejectReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
                (
                    "code",
                    models.SlugField(max_length=32, unique=True, verbose_name="Код"),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Заголовок")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Текст, который увидит владелец объявления.",
                        verbose_name="Пояснение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Причина отклонения",
                "verbose_name_plural": "Причины отклонения",
                "ordering": ["order", "code"],
            },
        ),
        migrations.CreateModel(
            name="ListingReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("fraud", "Мошенничество"),
                            ("sold", "Объект уже продан"),
                            ("wrong_info", "Недостоверная информация"),
                            ("duplicate", "Дубликат"),
                            ("spam", "Спам"),
                        ],
                        max_length=16,
                        verbose_name="Причина",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "is_resolved",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Разобрано"
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="catalog.listing",
                        verbose_name="Объявление",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listing_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто пожаловался",
                    ),
                ),
            ],
            options={
                "verbose_name": "Жалоба на объявление",
                "verbose_name_plural": "Жалобы на объявления",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["listing", "is_resolved"],
                        name="report_listing_open_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("listing", "reporter"),
                        name="listing_report_unique_reporter",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ModerationTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "В очереди"),
                            ("approved", "Одобрено"),
                            ("rejected", "Отклонено"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "checks",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Автопроверки"
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Количество сработавших автопроверок; жалобы дают 10.",
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, verbose_name="Комментарий модератора"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Когда решено"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_staff": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderation_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Модератор",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_tasks",
                        to="catalog.listing",
                        verbose_name="Объявление",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_moderation_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто решил",
                    ),
                ),
                (
                    "reject_reason",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderation_tasks",
                        to="catalog.rejectreason",
                        verbose_name="Причина отклонения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача модерации",
                "verbose_name_plural": "Очередь модерации",
                "ordering": ["-priority", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-priority", "created_at"],
                        name="moderation_queue_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "open")),
                        fields=("listing",),
                        name="moderation_single_open_task",
                    )
                ],
            },
        ),
    ]
