# Generated by Django 5.2.17 on 2026-08-22 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0016_reject_reasons"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingDailyStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="Дата")),
                (
                    "impressions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Показы в выдаче"
                    ),
                ),
                (
                    "views",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Открытия карточки"
                    ),
                ),
                (
                    "favourites",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Добавления в избранное"
                    ),
                ),
                (
                    "phone_reveals",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Показы телефона"
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_stats",
                        to="catalog.listing",
                        verbose_name="Объявление",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статистика объявления за день",
                "verbose_name_plural": "Статистика объявлений по дням",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["listing", "-date"], name="listing_stat_recent_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("listing", "date"), name="listing_daily_stat_unique"
                    )
                ],
            },
        ),
    ]
