# Generated by Django 5.2.17 on 2026-08-22 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0017_promotions"),
        ("users", "0007_seller_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="moderationtask",
            name="review",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moderation_tasks",
                to="users.review",
                verbose_name="Отзыв",
            ),
        ),
        migrations.AlterField(
            model_name="moderationtask",
            name="listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moderation_tasks",
                to="catalog.listing",
                verbose_name="Объявление",
            ),
        ),
        migrations.AddConstraint(
            model_name="moderationtask",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "open")),
                fields=("review",),
                name="moderation_single_open_review",
            ),
        ),
        migrations.AddConstraint(
            model_name="moderationtask",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("listing__isnull", False),
                    ("review__isnull", False),
                    _connector="OR",
                ),
                name="moderation_task_has_target",
            ),
        ),
    ]
