# Generated by Django 5.2.17 on 2026-08-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0018_seller_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="listingmedia",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="listingmedia",
            name="title",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Заголовок"
            ),
        ),
    ]
