# Generated by Django 5.2.17 on 2026-08-30 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0019_listingmedia_description_listingmedia_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="balcony_area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Балкон, м²",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="bathroom_area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Сан.узел, м²",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="bedroom_2_area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Спальная 2, м²",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="bedroom_area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Спальная, м²",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="furniture",
            field=models.CharField(
                blank=True, default="Полностью", max_length=50, verbose_name="Мебель"
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="hall_area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Холл, м²",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="has_direct_sale",
            field=models.BooleanField(default=True, verbose_name="Прямая покупка"),
        ),
        migrations.AddField(
            model_name="listing",
            name="has_mortgage",
            field=models.BooleanField(default=True, verbose_name="Ипотека"),
        ),
        migrations.AddField(
            model_name="listing",
            name="kitchen_area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Кухня, м²",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="landmarks",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Ключевые места"
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="living_room_area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Гостинная, м²",
            ),
        ),
    ]
