# Generated by Django 5.2.17 on 2026-08-30 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0020_listing_balcony_area_listing_bathroom_area_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Например: Гостинная, Холл, Кухня, Спальная, Гардеробная, Терраса, Сан.узел",
                        max_length=100,
                        verbose_name="Название комнаты",
                    ),
                ),
                (
                    "area",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Площадь, м²"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms_data",
                        to="catalog.listing",
                        verbose_name="Объявление",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комната",
                "verbose_name_plural": "Комнаты (экспликация помещений)",
                "ordering": ["order", "id"],
            },
        ),
    ]
