# Generated by Django 5.2.17 on 2026-08-31 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0021_listingroom"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="building_line",
            field=models.CharField(
                blank=True,
                choices=[
                    ("first", "Первая линия"),
                    ("second", "Вторая линия"),
                    ("inside", "Внутри квартала"),
                ],
                max_length=8,
                verbose_name="Линия",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="ceiling_height",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                verbose_name="Высота потолков, м",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="commercial_purpose",
            field=models.CharField(
                blank=True,
                choices=[
                    ("office", "Офис"),
                    ("shop", "Магазин"),
                    ("warehouse", "Склад"),
                    ("production", "Производство"),
                    ("catering", "Общепит"),
                    ("free", "Свободного назначения"),
                ],
                max_length=16,
                verbose_name="Назначение помещения",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="has_separate_entrance",
            field=models.BooleanField(default=False, verbose_name="Отдельный вход"),
        ),
        migrations.AddField(
            model_name="listing",
            name="plot_purpose",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ihs", "ИЖС"),
                    ("garden", "Садовый"),
                    ("agricultural", "Сельхозназначение"),
                    ("commercial", "Коммерческий"),
                ],
                max_length=16,
                verbose_name="Назначение участка",
            ),
        ),
    ]
