# Generated by Django 5.2.17 on 2026-08-31 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0022_kind_specific_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="condition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("euro", "Евроремонт"),
                    ("good", "Хорошее состояние"),
                    ("shell", "Под самоотделку"),
                    ("medium", "Среднее состояние"),
                    ("none", "Без ремонта"),
                ],
                max_length=16,
                verbose_name="Состояние и ремонт",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="exchange_possible",
            field=models.BooleanField(default=False, verbose_name="Возможен обмен"),
        ),
        migrations.AddField(
            model_name="listing",
            name="has_gas",
            field=models.BooleanField(default=False, verbose_name="Наличие газа"),
        ),
        migrations.AddField(
            model_name="listing",
            name="heating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("central", "Центральное"),
                    ("gas", "Газовое"),
                    ("electric", "Электрическое"),
                    ("autonomous", "Автономное"),
                ],
                max_length=16,
                verbose_name="Отопление",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="furniture",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full", "Полностью меблирована"),
                    ("partial", "Частично с мебелью"),
                    ("none", "Без мебели"),
                ],
                max_length=16,
                verbose_name="Мебель",
            ),
        ),
    ]
