# Generated by Django 5.2.17 on 2026-09-02 00:31

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    """Цена, площади и высота потолков — только положительные.

    Проверка на уровне поля, поэтому её видит и DRF (400 вместо записи), и
    админка, и любой `full_clean()`. Данные не переписываются: если в базе уже
    лежит отрицательная цена, миграция её не тронет — такие строки правятся
    вручную, автоматическая замена цены была бы хуже ошибки.
    """


    dependencies = [
        ("catalog", "0025_room_areas_to_listing_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Площадь, м²",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="ceiling_height",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Высота потолков, м",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="land_area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Площадь участка, соток",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Цена",
            ),
        ),
    ]
